version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=postres
      - POSTGRES_DB=PIDdatabase
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
#version: "3.7"
#services:
#  whale:
#    command: ["cowsay", "bye!"]